### ISSUE TITLE
Help!  "No device found"

### ISSUE THREAD

**Issue by zhangask** [coloz/cordova-plugin-esptouch#1]
When I use plugin, it not found device, but ESP8266 SmartConfig App can do.

**Comment by coloz** [comment]
android？ios？Please tell me the information about the platform, the system version and the Cordova version

**Comment by naushrambo** [comment]
Did not getting any response
Using on Android Cordova '8.0.0',

**Comment by coloz** [comment]
@naushrambo i use it on cordova-android 6.4.0
