### ISSUE TITLE
Can not sync with capacitor in ionic

### ISSUE THREAD

**Issue by TruongHaiDang** [coloz/cordova-plugin-esptouch#10]
I have a problem when use this plugin in ionic framework. When I run $npm i cordova-plugin-esptouch, I can not sync project with capacitor. 
$npx cap sync return this error:

[error] Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at /Users/truonghaidang/Documents/smart-config/node_modules/@capacitor/cli/dist/ios/update.js:285:40
    at Array.map (<anonymous>)
    at /Users/truonghaidang/Documents/smart-config/node_modules/@capacitor/cli/dist/ios/update.js:271:19
    at Array.map (<anonymous>)
    at copyPluginsNativeFiles (/Users/truonghaidang/Documents/smart-config/node_modules/@capacitor/cli/dist/ios/update.js:259:20)
    at Object.updateIOS (/Users/truonghaidang/Documents/smart-config/node_modules/@capacitor/cli/dist/ios/update.js:27:9)
    at async /Users/truonghaidang/Documents/smart-config/node_modules/@capacitor/cli/dist/tasks/update.js:65:13 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

Does anyone help me?. Thanks a lot

**Comment by coloz** [comment]
sorry, I haven't used capacitor

**Comment by jorgeAngulo** [comment]
Hi @TruongHaiDang did you fix the error?
If you didn't, are u trying to develop in android or ios?

**Comment by jorgeangulo97** [comment]
Hi @TruongHaiDang did you fix the error?
If you didn't, are u trying to develop in android or ios?

**Comment by TruongHaiDang** [comment]
> Hi @TruongHaiDang did you fix the error?
> If you didn't, are u trying to develop in android or ios?

Sorry, I gave up
