### ISSUE TITLE
新功能请求：建议新增esptouch-v2

### ISSUE THREAD

**Issue by angelofan** [coloz/cordova-plugin-esptouch#11]
建议新增esptouch-v2的配网功能。

我看到了你在 Espressif 的库中打开了一个issue：https://github.com/EspressifApp/EsptouchForAndroid/issues/75

我们现在新产品使用了ESP32的双模（蓝牙+WiFi）模块，发现 esptouch-v1 在很多路由器下无法配网（AP无线接入点是100%无法配网，普通的路由器大部分无法配网），并且发送邮件给 Espressif 报告问题，邮件截图如下：

首先，我们发现了此问题，并且开始向 Espressif 报告此问题
![image](https://user-images.githubusercontent.com/20255750/131058314-784e09ef-8f4a-4c4c-8037-f803b392016c.png)

随后，他们确定此问题存在，并且确认组播模式存在兼容性问题，他们更推荐广播模式。
![image](https://user-images.githubusercontent.com/20255750/131058385-509e49d2-3ff2-40b3-9252-d0cce1e490db.png)
![image](https://user-images.githubusercontent.com/20255750/131058439-927e3e8e-da32-4440-b5d7-ede76c13c68a.png)

随后，他们指定说该模块要用最新的App（即esptouch-v2）进行配网，他们可能已经打算停止维护esptouch-v1了。
![image](https://user-images.githubusercontent.com/20255750/131059809-c7e4070e-c6b0-443b-a299-ce7e83018b9b.png)

经过我们的测试，esptouch-v2的配网速度比esptouch-v1快很多，而且与各种路由器的兼容性很强。

当 Espressif 发布esptouch-v2时，所有新的模组就会与它兼容，并且默认推荐esptouch-v2配网。在不久后，esptouch-v1可能会逐渐被弃用。

esptouch-v1关于批量配网的实现：
- 广播模式在发现一个设备后立马停止了配网，组播模式可以自定义配网数量。
- 广播模式理论上也可以在发现设备并自动停止配网后，再次调用开始配网的方式，实现“伪”批量配网，但是这种方法耗时比较长，如果同时添加5个设备大概要2-3分钟。
- 组播模式对于批量配网就很适合，只要我开始配网时定义的待配网设备数量足够大（比如999），在配合超时设定，就可以实现批量配网的功能。

esptouch-v2的批量配网功能非常好。

所以，请考虑新增esptouch-v2的配网功能。

**Comment by angelofan** [comment]
参考 Espressif 库：
- https://github.com/EspressifApp/lib-esptouch-v2-android
- https://github.com/EspressifApp/EsptouchForAndroid/tree/v2.0.0/esptouch-v2
- https://github.com/EspressifApp/EsptouchForIOS/tree/v2.0.0

**Comment by coloz** [comment]
esptouch app lib的问题，存在太久了，官方根本不理会，我已经不想吐槽了。我们现在方案也是以AP配网为主。
另外，v2出来我就关注了，但我主要使用的是esp arduino sdk，arduino sdk还没有提供v2支持，所以我还没做适配，等arduino sdk支持了v2，我会做支持。

**Comment by angelofan** [comment]
esp arduino sdk有没有v2的开发计划？我们在开发新产品，为了以后的兼容性，我们需要使用v2的esptouch功能，并且我们App依赖cordova-android 9.0.0和cordova-ios 5.1.1，因此可能需要esptouch-v2向下兼容。我想问一下此库是否计划在近期进行v2版本的开发，这是否有难度？如果可以，我愿意以我个人名义为此项目的v2开发捐助一些。如果开发的时间投入预算比较长，请告诉我，我会再次考虑是否在我们的新产品中使用esptouch-v2的功能。

**Comment by coloz** [comment]
不清楚arduino sdk什么时候支持，等其支持了，我才会写v2支持

**Comment by angelofan** [comment]
好的

**Comment by coloz** [comment]
@angelofan 已经更新esptouch v2了，我用esp32c3测试是可以的。目前只写了android部分，ios的空了再写了，欢迎测试反馈

**Comment by coloz** [comment]
ios的也添加了，先把这个issues关了，遇到问题再提。

**Comment by angelofan** [comment]
我也使用esp32c3搭配测试了，Android可以完美的运行，iOS的开发工具要更新，稍后更新完了就测试。

此更新很棒！

另外有些问题：
- `customData` 的数据类型是什么？字符串吗？还是JSON格式字符串，还是对象格式呢？
- 我看到v2版本没有使用 `bssid` 了吗，我在乐鑫的库文档里看到 `AP's BSSID, nonnull` 的注释（详见 https://github.com/EspressifApp/lib-esptouch-v2-android/blob/main/esptouch-v2/README.md 的 `Start provisioning` 部分），有没有影响？
- `aesKey` 目前没有设定项，是否会在未来加入此支持？

非常感谢你为开源作出如此贡献，我很喜欢这个仓库，做的很棒！

**Comment by coloz** [comment]
1. esptouch v2 允许在传输ssid等信息的同时，传输一个自定义数据customData。可用作设备密钥传输；  
2. esptouch本身有，因为我用不到，所以没写，以后有空加上；  
3. 同上。

**Comment by angelofan** [comment]
1. 这个customData不限制数据类型吗？比如字符串、数字、对象、字节流等。这个建议在文档中写出。
2. 在v1中不传bssid会报错，不知道v2为什么没有传还能正常运行。可能v1中要求bssid是因为可以防止同ssid的问题。不知道乐鑫底层遇到同ssid的时候没有bssid校验会不会出错，有些家庭多个路由器设置相同的ssid和密码。

**Comment by coloz** [comment]
1. 可以咨询下你做硬件的同事，就不会纠结类型问题了，这里仅限制最大长度127  
2. v1 bssid全设为0即可，v2允许为空，至于连哪个，不纠结，我猜他会连信号更好的（没看idf源码，有兴趣你可以看看）。即使有bssid，也是你手机连接的信号更好的那个，所以区别不大。

**Comment by angelofan** [comment]
OK，非常感谢耐心解答。
