### ISSUE TITLE
Update EspTouch lib - UDP bug

### ISSUE THREAD

**Issue by christiangelone** [coloz/cordova-plugin-esptouch#12]
Hi 😄 
Can you update de esptouch lib?  An UDP bug fix has been made for iOS 14.5 and if not, this plugin wont work for iOS devices!

**Comment by coloz** [comment]
Sorry, I only have only one ios12 device. I can't reproduce this problem

**Comment by mogupta** [comment]
@coloz  I tried on iOS 14.6 and I can confirm and reproduce the problem. Can you guide me what steps to take to upgrade this plugin ? 
I tried https://github.com/EspressifApp/EsptouchForIOS . It works flawlessly , they have a fix for it.

**Comment by mogupta** [comment]
Do we just need to update the .a lib file ? if yes how to can I get it ?

**Comment by coloz** [comment]
@mogupta @christiangelone I have updated the plugin to esptouch v2,  but the IOS part hasn't been written.
Because I don't have more iPhones for testing,The new version will been test my iPhone X with IOS 15 only.

**Comment by mogupta** [comment]
You mean you have tested the esp touch V-2 with iPhone X on IOS15? What about Android ?
Thanks @coloz

**Comment by angelofan** [comment]
@mogupta Android 8.0.0 is OK. I have tested it.
