### ISSUE TITLE
iOS 16 Unable to pair with Smart config. 

### ISSUE THREAD

**Issue by mogupta** [coloz/cordova-plugin-esptouch#14]
Using ESPtouch with ESP8266.  Updated to master branch . Even then smart config not working. 
My iPhone version 16.1.2

Please advise.

**Comment by mogupta** [comment]
Works with https://apps.apple.com/us/app/espressif-esptouch/id1071176700

**Comment by coloz** [comment]
The same problem as before, I do not have the IOS16 of equipment for testing,so,it cannot be updated in a short time

**Comment by mogupta** [comment]
Bug 1 

in esptouch.js , you have modified esptouch.js file with start function parameters as apSsID and apPassword but in esptouch.m you are using old parameters

```
start: function (apSsid, apPassword, successCallback, failCallback) {
    exec(successCallback, failCallback, "esptouch", "start", [apSsid, apPassword]);
  },
  },
```

```
- (void) start:(CDVInvokedUrlCommand *)command{
    [self.commandDelegate runInBackground:^{
        dispatch_queue_t  queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
        
        [self._condition lock];
        callback_ID = command.callbackId;
        NSString *apSsid = (NSString *)[command.arguments objectAtIndex:0];
        NSString *apBssid = (NSString *)[command.arguments objectAtIndex:1];
        NSString *apPwd = (NSString *)[command.arguments objectAtIndex:2];
        int taskCount = [[command.arguments objectAtIndex:3] intValue];
        NSString *broadcastData =  (NSString *)[command.arguments objectAtIndex:4];
        BOOL isbroadcastData = true;
```

**Comment by mogupta** [comment]
Bug 2 - Fixing the first bug triggers the start function . But with the following error occurring ### repeatedly
```
client: sendto fail, but just ignore it
: No route to host
```

**Comment by mogupta** [comment]
@coloz please suggest something. How can I fix it ? May be you can access my device using anydesk ?

**Comment by mogupta** [comment]
@coloz found solution , just add the following line 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/479667/217999276-bf762897-dec9-4779-a403-48f93c6d2b2a.png">

**Comment by mogupta** [comment]
PR #15 fixes the issue

**Comment by angelofan** [comment]
@coloz Ready to publish to npm?
