### ISSUE TITLE
Android：错误: 从内部类中访问本地变量apSsid; 需要被声明为最终类型

### ISSUE THREAD

**Issue by angelofan** [coloz/cordova-plugin-esptouch#3]
@coloz 我刚刚用程序做了一个demo，只添加了你的插件，运行在ionic3框架上，然后编译时抛出一个问题。

用ionic3安装插件后，编译到Android studio上面时，报错：
```
错误: 从内部类中访问本地变量apSsid; 需要被声明为最终类型
错误: 从内部类中访问本地变量apPassword; 需要被声明为最终类型
错误: 从内部类中访问本地变量taskResultCount; 需要被声明为最终类型
```
平台信息：
```
ionic版本：CLI 4.10.3
cordova版本：8.1.2
npm版本：6.4.1
错误类型：编译时出错
```

为了让全球朋友发现和一起探讨这个问题，下面附上英文版本：

In order for global friends to discover and discuss this issue together, the English version is attached below:

After installing the plugin with ionic3, when compiling to Android studio, I get an error:
```
Error: Accessing the local variable apssid from the inner class; needs to be declared as the final type
Error: Access local variable apPassword from inner class; need to be declared as final type
Error: accessing the local variable taskResultCount from the inner class; needs to be declared as the final type
```
Platform information:
```
Ionic version: CLI 4.10.3
Cordova version: 8.1.2
Npm version: 6.4.1
Error type: Error compiling
```

**Comment by coloz** [comment]
上个issues中回复过了，请使用1.0.4，1.0.4之后我只写了android版本，因为没mac，暂时无法写ios版本。
readme中有写，如果cordova android版本<7.0.0，需要使用1.0.3
插件主要看cordova android、cordova ios版本、android ios版本，能否使用和ionic cli、cordova cli、npm等版本几乎无关

**Comment by angelofan** [comment]
@coloz 因为最新的线上版本是1.0.5，这个版本Android编译时就不通过，还没有run到真机上。真机Android版本是8.1版本，我是否要切换到1.0.4的插件版本？

**Comment by coloz** [comment]
对于java，我也是现学现用，不太清楚你那里为啥会报这个错误，因为我这边测试是没问题的，所以暂时不改了。你可以自己尝试给报错的变量加上final应该就可以了。

**Comment by angelofan** [comment]
恩，打酱油地问一下，你在这里的原始代码是final string，你修改后是byte[]，看到你这个目的是增加中文ssid的支持，这个byte[]是不是要写成final byte[] ？因为我是使用TypeScript（类似于JavaScript）调用的cordova插件，无法使用java语法在调用时前面加final，我也不懂java，只是看到有这个区别

![image](https://user-images.githubusercontent.com/20255750/54533950-503c6b80-49c6-11e9-8606-6db6c9167a28.png)

我刚才退回到1.0.4版本编译了一下，是可以通过的，没有任何问题。

感谢你的回复

**Comment by coloz** [comment]
android studio打开项目，找到esptouch.java,添加final即可
