### ISSUE TITLE
Plugin doesn't work with Ionic 3

### ISSUE THREAD

**Issue by dualtime** [coloz/cordova-plugin-esptouch#4]
We have a made a simple app to list networks and start the configuration and ultimately stop it.
Like this, with 3 simple buttons calling your plugin's methods.

![image](https://user-images.githubusercontent.com/15659519/55020185-3dd9b780-4fee-11e9-9f64-e56fef04ef07.png)

We have also made a provider which calls the functions.

```import { Injectable } from '@angular/core';
import { Plugin, Cordova, CordovaProperty, CordovaInstance, IonicNativePlugin } from "@ionic-native/core";



@Plugin({
  pluginName: "espSmartconfig",
  pluginRef: "espSmartconfig",
  plugin: "cordova-plugin-smartconfig",
  repo: "https://github.com/IOCare/cordova-plugin-smartconfig.git",
  platforms: ["Android", "iOS"]
})

@Injectable()
export class NetworkProvider {
  constructor() {
    console.log("Initialized Network provider")
  `}`
  @Cordova()
  startConfig(apSsid, apBssid, apPassword, isSsidHiddenStr, taskResultCountStr, successCallback, errorCallback) {
    return;
  }
  @Cordova()
  stopConfig(successCallback, errorCallback) {
    return;
  }
  @Cordova()
  getNetworklist([options]: any, listHandler, fail) {
    return;
  }
}`

The response from the three methods are the ones you can see on the image on the console which is on the right side. 
On the network list it returns an empty array.
On the stopConfig returns Cancel Success.
And on the startConfig after a few seconds/minutes returns No device found.

We have tried with cordova-android 7.1.1 and cordova-android 6.4.0 as well.

Are we missing something?

**Comment by coloz** [comment]
I haven't tried use @Plugin，the plugin is all right by direct using.
You can test the git version，It's the latest

**Comment by dualtime** [comment]
Hello again,

We have created a repo with an ionic app with this plugin.
You can check it here: https://github.com/dualtime/ionicEspTouch

We are calling it directly as you proposed and it isn't working as well.

Our ionic info outputs:

![image](https://user-images.githubusercontent.com/15659519/55076135-952e6500-508c-11e9-89e9-90624d8afae4.png)


Can you please help us get this plugin working?

**Comment by coloz** [comment]
cordova-android < 7.0.0   
need to use 1.0.3, and read the readme 
https://github.com/coloz/cordova-plugin-esptouch/tree/abec5cd8f09e91d8abb9bf7ab2273270e6670efb

**Comment by dualtime** [comment]
We have already tried with version 1.0.3 on cordova-android 6.4.0
And with versions 1.03, 1.04, 1.05 and 1.06 on cordova-android 7.1.4

We haven't been able to have a working app yet. The results are as we have shown you on this issue.
Could you please provide us a simple working example with ionic 3?

**Comment by coloz** [comment]
Please read the readme. The parameters of 1.0.3 are different.
https://github.com/coloz/cordova-plugin-esptouch/tree/abec5cd8f09e91d8abb9bf7ab2273270e6670efb

**Comment by dualtime** [comment]
Be that as it may, we are not able to get it working. 
And we need cordova-android version 7.1.4.

Could you please provide us a simple working app with this cordova-android version?

Also it would be nice if you could test our app we have on github and give us feedback. 

We appreciate if you do so because we need to get this working.

**Comment by coloz** [comment]
1.I've seen your project. Your project uses cordova-android 6.4.0 and plugin 1.0.3.
2.if  cordova-android >7.0.0,You can test the latest version on my github，It's the latest

**Comment by coloz** [comment]
根据readme所示方法调用即可：
1.0.3：https://github.com/coloz/cordova-plugin-esptouch/tree/abec5cd8f09e91d8abb9bf7ab2273270e6670efb
latest：https://github.com/coloz/cordova-plugin-esptouch/blob/1.0.6/README.md

**Comment by dualtime** [comment]
I already said we tried both ways. 
Even with cordova-android 6.4.0 and plugin version 1.0.3 we don't get the expected results. Even with cordova-android 7.1.4 and your plugin version 1.0.6 we don't get any results. Is it needed to create another repo with different versions???
Did you get your plugin working with our app?

**Comment by coloz** [comment]
It's normal for me to use my plugin
As I've said, I've seen your project, your project uses 1.0.3, but the parameters are the latest version.
My English is not good. If you can't understand what I'm saying, I'm already sorry.
I can only say that this plugin is normal.

**Comment by dualtime** [comment]
Follow the steps in .readme. 
We have updated the readme, there was a typo. We need to use version 7.1.4 of cordova-android which means that we also need 1.0.6 of your plugin, correct?
Can you please test our app and tell us if it works or not?

**Comment by coloz** [comment]
抱歉我不会测试的，我已经告诉你程序错误的地方了，请你先修改后自行测试

**Comment by dualtime** [comment]
Are the parameters we pass correct for version 1.0.6 ?
If it isn't, please tell us what it is wrong.

**Comment by angelofan** [comment]
@dualtime Hey,
Does this problem still bother you? My app uses this plugin and it works very well now. If necessary, I can separate the code for this plugin from my project and upload it to repo for your reference.

**Comment by angelofan** [comment]
@dualtime You can refer to the fork I just created and have already written the reference code to the README.

[https://github.com/13546777510/cordova-plugin-esptouch](https://github.com/13546777510/cordova-plugin-esptouch)

**Comment by dualtime** [comment]
Hello @13546777510,
Yes, this problem still bother us. Is your app developed in ionic framework as well ?

**Comment by angelofan** [comment]
@dualtime 
yes, my app is work with ionic3, and it works well with this plugin. you can read my fork's readme, and if you have anymore issues, i will be help you.
[https://github.com/13546777510/cordova-plugin-esptouch](https://github.com/13546777510/cordova-plugin-esptouch)

**Comment by dualtime** [comment]
Ok, thanks. We will take a look into it as soon as possible.

**Comment by angelofan** [comment]
OK, If you still don't understand how to do this, I can create a demo that will run successfully for your reference. To do this, you can try to do it according to the readme documentation. If you have any problems, I will create a demo.

**Comment by angelofan** [comment]
@dualtime I found an existing demo for this plug. You can refer to this
[https://github.com/dualtime/ionicEspTouch](https://github.com/dualtime/ionicEspTouch)

**Comment by dualtime** [comment]
@13546777510 Hello again. That demo you've found is the one which doesn't work and was made by our team. We will take a look into you repo. Thanks.

**Comment by dualtime** [comment]
@13546777510 
Hello Angelo,
Could we please have a skype call to understand what are we doing wrong? 
We can't get it to work as we expect.

**Comment by angelofan** [comment]
@dualtime Sorry, I don't have a very good level of spoken English for video chat. Do you use WeChat, you can add my WeChat to talk on the spot. Here is my WeChat id, you can add me by "scanning" my QR code in the upper right corner of the WeChat app "+", waiting for your addition

![image](https://user-images.githubusercontent.com/20255750/60721598-108f9480-9f61-11e9-8228-460db92a0b93.png)

**Comment by dualtime** [comment]
@13546777510 
Thanks, I already sent the invitation.

**Comment by coloz** [comment]
> 根据readme所示方法调用即可：
> 1.0.3：https://github.com/coloz/cordova-plugin-esptouch/tree/abec5cd8f09e91d8abb9bf7ab2273270e6670efb
> latest：https://github.com/coloz/cordova-plugin-esptouch/blob/1.0.6/README.md

I think the Readme clearly shows how to use the plugin.  
a few months passed,hasn't it worked yet?  
This is a basic knowledge that everyone knows，that if code does not work, the error message will tell you reason, but you never showed the error message again.
