### ISSUE TITLE
App crashes on ios 12.2 

### ISSUE THREAD

**Issue by assafWifiWall** [coloz/cordova-plugin-esptouch#5]
Hello,
Tested the plugin on ios >= 12.2 with an iPhone 7 and the app crashes once I call esptouch.start()
On lower iOS versions it seems to work OK.
Compiled with xcode 10.1.

I would love to know if someone else had countered the same issue.
Any help would be very much appreciated,
Thank you.

**Comment by coloz** [comment]
I've heard that some plugins are not working on ios 12.2,
but, my macbook was taken away by colleague and temporarily unable to debug

**Comment by assafWifiWall** [comment]
Hi, thank you for your reply.
I managed to run the app on Xcode, here is the debug output:
(Looks like it crashes on esptouch.m line 38 -- (void) start:(CDVInvokedUrlCommand *) ...)

Output:
2019-05-30 18:55:11.387234+0300 WifiWall[757:52439] Welcome Esptouch v0.3.7.0
2019-05-30 18:55:11.387342+0300 WifiWall[757:52439] ESPTouchTask init
2019-05-30 18:55:11.404609+0300 WifiWall[757:52439] -[NSNull componentsSeparatedByString:]: unrecognized selector sent to instance 0x1cda199d0
2019-05-30 18:55:11.415235+0300 WifiWall[757:52439] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull componentsSeparatedByString:]: unrecognized selector sent to instance 0x1cda199d0'
*** First throw call stack:
(0x19d951ea4 0x19cb21a50 0x19d86ab14 0x19d9577bc 0x19d95946c 0x1010a12f4 0x1010a2fdc 0x1010a38b4 0x101047b0c 0x1013d3824 0x1013d4dc8 0x1013d7c90 0x1013e61dc 0x1013e6bc8 0x19d56d17c 0x19d56fcec)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by wx85105157** [comment]
> 嗨，谢谢你的回复。
> 我设法在Xcode上运行应用程序，这是调试输出:( 
> 看起来它在esptouch.m第38行崩溃 - （void）start：（CDVInvokedUrlCommand *）...）
> 
> 输出：
> 2019-05-30 18：55：11.387234 + 0300 WifiWall [757：52439]欢迎使用Esptouch v0.3.7.0 
> 2019-05-30 18：55：11.387342 + 0300 WifiWall [757：52439] ESPTouchTask init 
> 2019-05 -30 18：55：11.404609 + 0300 WifiWall [757：52439] - [NSNull componentsSeparatedByString：]：无法识别的选择器发送到实例0x1cda199d0 
> 2019-05-30 18：55：11.415235 + 0300 WifiWall [757：52439] ***终止应用因未捕获的异常'NSInvalidArgumentException'，原因是： ' - [NSNull componentsSeparatedByString：]：无法识别的选择发送到实例0x1cda199d0' 
> ***第一掷调用堆栈：
> （0x19d951ea4 0x19cb21a50 0x19d86ab14 0x19d9577bc 0x19d95946c 0x1010a12f4 0x1010a2fdc 0x1010a38b4 0x101047b0c 0x1013d3824 0x1013d4dc8 0x1013d7c90 0x1013e61dc 0x1013e6bc8 0x19d56d17c 0x19d56fcec）
> libc ++ abi.dylib：以NSException类型的未捕获异常终止
> （lldb）

test on iphone6s 12.1.4 and iphone6s 12.3.1.The plugin works fine

**Comment by wx85105157** [comment]
test iphonex 12.3.1 fine
We do not have IOS 12.2

**Comment by coloz** [comment]
We tested it on IOS 12.3 and the plug-in works well.
test device: iphone 6 / iphone X.
It is recommended that you check your code, if call the plugin repeatedly.

**Comment by assafWifiWall** [comment]
Thank you, also confirmed on iOS 12.2 now.
I'm trying to figure out what was the issue, I recompiled with a fresh ionic project and it works.
