### ISSUE TITLE
Appstore connect operation error

### ISSUE THREAD

**Issue by mogupta** [coloz/cordova-plugin-esptouch#6]
When I archiving and uploading the ipa, it gives the following error. I tried with xcode 10.1

![image](https://user-images.githubusercontent.com/479667/62546037-67e69480-b880-11e9-9266-696860a68b37.png)

**Comment by coloz** [comment]
It doesn't seem like a plugin issuse.
It is recommend that you should use the latest version of the xcode

**Comment by mogupta** [comment]
Issue resolved. It was something stupid at my end
