### ISSUE TITLE
Cannot compile for arm7 and arm7s

### ISSUE THREAD

**Issue by mogupta** [coloz/cordova-plugin-esptouch#7]
Hi When compiling for arm7 and arm7s (IOS).  An error is thrown that the library is not compiled for arm7 and arm7s . It compiles fine for arm64. I think libEsptouch_v0.3.7.0.a was not compiled for arm7 . Please advise.

**Comment by coloz** [comment]
iphone4 is arm7, it is too old,no plans to support,My oldest device is iphone6.
